CREATE USER 'kys_lisa'@'%' IDENTIFIED BY  '***';

GRANT ALL PRIVILEGES ON * . * TO  'kys_lisa'@'%' IDENTIFIED BY  '***' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON  `kys_lisa` . * TO  'kys_lisa'@'%'